### ISSUE TITLE
Builtin `type` can be used for .mlapp -> .m conversion on new MATLAB

### ISSUE THREAD

**Issue by Dev-iL** [StackOverflowMATLABchat/mlapp2classdef#8]
This basically saves us the hassle of unzipping and stripping of the xml...

This functionality was probably added in MATLAB R2016a with the release of the App Designer, so regex-based code is probably still relevant when converting using older versions.

**Comment by sco1** [comment]
Interesting, good find!

I just tested that using `diary` to pipe the output to an `*.m` file functions correctly, but it adds leading and trailing `diary` commands that need to be removed. It can also be piped to a string with `evalc` and written to a file with `fprintf`, which may be the most time expedient option.

I'll add in a check for versions >= R2016a to utilize one of these options to avoid the overhead of unzipping.

**Comment by sco1** [comment]
`type` works on `*.mlapp` files in R2015b as well, I don't have any other old versions to test with.

**Comment by Dev-iL** [comment]
Just tested on 2015a - works.

**Comment by Dev-iL** [comment]
@AnderBiguri [tested this on 2014b](http://chat.stackoverflow.com/transcript/message/30313531) and it still works. @adeak [tested it on 2012b](http://chat.stackoverflow.com/transcript/message/30313564) and it doesn't.

**Comment by sco1** [comment]
The App Designer tech preview was released in October 2014, so I was thinking R2014b or R2014a would have been the earliest they'd start incorporating support. I'll set the flag to R2014b for now.

**Comment by sco1** [comment]
Should be in now but the regular expressions will need to be compared between versions. The "old" MATLAB handling reads every line of the XML file into its own cell but the `type` approach reads everything into a single character array.
